# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Npm publish

on:
    push:
        branches:
            - main

permissions:
    contents: write
    pull-requests: write
    id-token: write
    issues: write

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Check NPM Token
              # id: check_token
              run: |
                  if [ -z "${{ secrets.NPM_TOKEN }}" ]; then
                    echo "NPM_TOKEN is not set"
                    exit 1
                  else
                    echo "NPM_TOKEN is set"
                  fi

            - uses: googleapis/release-please-action@v4
              id: release
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  release-type: node
                  #   target-branch: main

            - name: Setup Node.js
              uses: actions/setup-node@v4
              if: ${{ steps.release.outputs.release_created }}
              with:
                  node-version: 18
                  registry-url: https://registry.npmjs.org/

            - name: Install dependencies
              if: ${{ steps.release.outputs.release_created }}
              run: npm ci

            - name: Build
              if: ${{ steps.release.outputs.release_created }}
              run: npm run build

            - name: Publish to NPM
              if: ${{ steps.release.outputs.release_created }}
              run: npm publish --provenance --access public
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
